version: '3.8'

name: metric
services:
    postgres:
        container_name: metric-postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "5432:5432"

    server:
        container_name: metric-server
        build:
            context: .
        command: server
        env_file:
            - .env.server
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    agent:
        container_name: metric-agent
        build:
            context: .
        command: agent
        env_file:
            - .env.agent
        depends_on:
            - postgres
            - server